# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1920, 1080)
        self.video_label = QtWidgets.QLabel(Form)
        self.video_label.setGeometry(QtCore.QRect(160, 220, 640, 480))
        font = QtGui.QFont()
        font.setPointSize(50)
        self.video_label.setFont(font)
        self.video_label.setAlignment(QtCore.Qt.AlignCenter)
        self.video_label.setObjectName("video_label")
        self.capture_label = QtWidgets.QLabel(Form)
        self.capture_label.setGeometry(QtCore.QRect(1120, 220, 640, 480))
        font = QtGui.QFont()
        font.setPointSize(50)
        self.capture_label.setFont(font)
        self.capture_label.setAlignment(QtCore.Qt.AlignCenter)
        self.capture_label.setObjectName("capture_label")
        self.result_label = QtWidgets.QLabel(Form)
        self.result_label.setGeometry(QtCore.QRect(340, 800, 470, 150))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.result_label.setFont(font)
        self.result_label.setStyleSheet("color:rgb(255, 0, 0);")
        self.result_label.setText("")
        self.result_label.setAlignment(QtCore.Qt.AlignCenter)
        self.result_label.setObjectName("result_label")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(160, 800, 140, 150))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(1120, 800, 140, 150))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.status_label = QtWidgets.QLabel(Form)
        self.status_label.setGeometry(QtCore.QRect(1300, 800, 470, 150))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.status_label.setFont(font)
        self.status_label.setStyleSheet("color:rgb(255, 0, 0);")
        self.status_label.setAlignment(QtCore.Qt.AlignCenter)
        self.status_label.setObjectName("status_label")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(440, 60, 1000, 100))
        font = QtGui.QFont()
        font.setPointSize(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.video_label.setText(_translate("Form", "宣传视频"))
        self.capture_label.setText(_translate("Form", "拍摄图像"))
        self.label_3.setText(_translate("Form", "识别结果:"))
        self.label_4.setText(_translate("Form", "投放状态:"))
        self.result_label.setText(_translate("Form", "无垃圾"))
        self.status_label.setText(_translate("Form", "NONE"))
        self.label_6.setText(_translate("Form", "智能垃圾分类"))
